version: '3'

services:
  matching:
    build: 
      context: .
      dockerfile: matching/Dockerfile
    environment:
      - ENVIRONMENT=dev
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service_account_credentials.json
    volumes:
      - ./credentials:/credentials
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=communityp
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SCHEMA=alh_community_platform
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=communityp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 