version: '3'

services:
  matching:
    build: 
      context: .
      dockerfile: apps/matching/Dockerfile
    environment:
      - ENVIRONMENT=development
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service_account_credentials.json
    volumes:
      - ./credentials:/credentials
      - ./config:/config
    ports:
      - "8080:8080"
    depends_on:
      - db

  web-gateway:
    build: 
      context: .
      dockerfile: apps/web_gateway/Dockerfile
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./public_config:/public_config
      - ./config:/config
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=communityp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: