
line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = [
    "ALL"
]

[lint.per-file-ignores]
"__init__.py" = [
    "D104"
]
"**/tests/*" = [
    "ANN",
    "D100",
    "D103",
    "INP001",
    "S101",
]

[format]
quote-style = "double"
indent-style = "space"