POST http://localhost:8080/meetings/create
Content-Type: application/json

{
  "description": "test_meeting",
  "location": "Blue Oyster Bar",
  "scheduled_time": "2024-11-11T11:11:11",
  "organizer_id": 1
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 400");
    });
    client.global.set("created_meeting_id", response.body.id);

%}

###

PATCH http://localhost:8080/meetings/{{created_meeting_id}}
Content-Type: application/json

{
  "description": "test_meeting_updated",
  "location": null,
  "scheduled_time": null,
  "organizer_id": 1
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 400");
    });
    client.test("description updated", function () {
        client.assert(response.body["description"] === "test_meeting_updated", "value is wrong");
    });

%}

###

PATCH http://localhost:8080/meetings/{{created_meeting_id}}
Content-Type: application/json

{
  "description": "test_meeting_updated_v2",
  "location": null,
  "scheduled_time": null,
  "organizer_id": 2
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 403, "Response status is not 400");
    });
%}

###

GET http://localhost:8080/meetings/{{created_meeting_id}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 400");
    });
    client.test("description updated", function () {
        client.assert(response.body["description"] === "test_meeting_updated", "value is wrong");
    });

%}
