[project]
name = "common-db"
version = "0.1.6"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "und3v3l0p3d", email = "prohibitme@ya.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "config-library",
    "pydantic>=2.10.4",
    "pydantic-settings>=2.7.0",
    "sqlalchemy[asyncio]>=2.0.36",
    "alembic>=1.13.1",
    "psycopg2-binary>=2.9.9", # For running migrations
    "pydantic_extra_types>=0.1.0",
    "pydantic[email]>=2.10.6",
    "pycountry>=23.1.14",
    "tzdata>=2025.1",
    "pydantic[email]>=2.10.6",
    "fastapi>=0.115.11",
]

[project.scripts]
common-db = "common_db:main"

# Add package data configuration
[tool.setuptools.package-data]
common_db = [
    "alembic.ini",
    "migrations/script.py.mako"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
    "black>=24.2.0",
]

[tool.ruff]
extend = "../../ruff.toml"

[tool.uv.sources]
config-library = { path = "../config_library" }
