[project]
name = "vacancies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "cloud-sql-python-connector[asyncpg]>=1.15.0",
    "langchain-google-vertexai>=2.0.10",
    "loguru>=0.7.3",
    "playwright>=1.49.1",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.7.1",
    "sqlalchemy>=2.0.37",
]

[tool.uv]
dev-dependencies = [
    "browser-use>=0.1.8",
    "debugpy>=1.8.11",
    "jsonpatch>=1.33",
    "jupyter>=1.1.1",
    "ruff>=0.9.1",
]
