steps:
- name: 'docker'
  #
  args: ['build', '--build-context', 'root_dir=''/workspace''', '-t',
    'us-east4-docker.pkg.dev/communityp-440714/cloud-run-source-deploy/community_platform/community-platform:$COMMIT_SHA', '.']
  dir: 'apps/web_gateway'
  volumes:
    - name: 'vol1'
      path: '/workspace'
images:
- 'us-east4-docker.pkg.dev/communityp-440714/cloud-run-source-deploy/community_platform/community-platform:$COMMIT_SHA'
options:
 logging: CLOUD_LOGGING_ONLY