steps:
- name: 'docker'
  args: ['build', '--build-context', 'root=''../../''', '-f', 'apps/web_gateway/Dockerfile', '-t',
    'us-east4-docker.pkg.dev/communityp-440714/cloud-run-source-deploy/community_platform/community-platform:$COMMIT_SHA', '.']
images:
- 'us-east4-docker.pkg.dev/communityp-440714/cloud-run-source-deploy/community_platform/community-platform:$COMMIT_SHA'
options:
 logging: CLOUD_LOGGING_ONLY