"""added initial linkedin and enums

Revision ID: 42da6d4c9ab3
Revises: 0415dc958fef
Create Date: 2025-01-22 11:42:08.433080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42da6d4c9ab3"
down_revision: Union[str, None] = "0415dc958fef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "connects",
                "referrals_recommendation",
                "mentoring_mentor",
                "mentoring_mentee",
                "mock_interview",
                "projects_find_contributor",
                "projects_find_cofounder",
                "projects_pet_project",
                name="form_intent_type_enum",
                schema="alh_community_platform",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("calendar", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"alh_community_platform.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="alh_community_platform",
    )
    op.create_index(
        "ix_form_intent_type",
        "forms",
        ["intent"],
        unique=False,
        schema="alh_community_platform",
    )
    op.create_table(
        "linkedin_profiles",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("users_id_fk", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("occupation", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("profile_url", sa.String(), nullable=False),
        sa.Column("profile_picture", sa.String(), nullable=True),
        sa.Column("connections_count", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("twitter", sa.String(), nullable=True),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("endorsements", sa.JSON(), nullable=False),
        sa.Column("certifications", sa.JSON(), nullable=False),
        sa.Column("volunteer_work", sa.JSON(), nullable=False),
        sa.Column("publications", sa.JSON(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["users_id_fk"],
            ["alh_community_platform.users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("users_id_fk"),
        schema="alh_community_platform",
    )
    op.create_index(
        "idx_profile_created",
        "linkedin_profiles",
        ["created_at"],
        unique=False,
        schema="alh_community_platform",
    )
    op.create_index(
        "idx_profile_name_location",
        "linkedin_profiles",
        ["full_name", "country", "city"],
        unique=False,
        schema="alh_community_platform",
    )
    op.create_index(
        op.f("ix_alh_community_platform_linkedin_profiles_profile_id"),
        "linkedin_profiles",
        ["profile_id"],
        unique=False,
        schema="alh_community_platform",
    )
    op.create_index(
        op.f("ix_alh_community_platform_linkedin_profiles_username"),
        "linkedin_profiles",
        ["username"],
        unique=True,
        schema="alh_community_platform",
    )
    op.create_table(
        "linkedin_education",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("school", sa.String(), nullable=False),
        sa.Column("degree", sa.String(), nullable=True),
        sa.Column("field_of_study", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=True),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["alh_community_platform.linkedin_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="alh_community_platform",
    )
    op.create_index(
        "profile_id",
        "linkedin_education",
        [],
        unique=True,
        schema="alh_community_platform",
    )
    op.create_table(
        "linkedin_experience",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company_linkedin_url", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=True),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["alh_community_platform.linkedin_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="alh_community_platform",
    )
    op.create_index(
        "profile_id",
        "linkedin_experience",
        [],
        unique=True,
        schema="alh_community_platform",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "profile_id",
        table_name="linkedin_experience",
        schema="alh_community_platform",
    )
    op.drop_table("linkedin_experience", schema="alh_community_platform")
    op.drop_index(
        "profile_id",
        table_name="linkedin_education",
        schema="alh_community_platform",
    )
    op.drop_table("linkedin_education", schema="alh_community_platform")
    op.drop_index(
        op.f("ix_alh_community_platform_linkedin_profiles_username"),
        table_name="linkedin_profiles",
        schema="alh_community_platform",
    )
    op.drop_index(
        op.f("ix_alh_community_platform_linkedin_profiles_profile_id"),
        table_name="linkedin_profiles",
        schema="alh_community_platform",
    )
    op.drop_index(
        "idx_profile_name_location",
        table_name="linkedin_profiles",
        schema="alh_community_platform",
    )
    op.drop_index(
        "idx_profile_created",
        table_name="linkedin_profiles",
        schema="alh_community_platform",
    )
    op.drop_table("linkedin_profiles", schema="alh_community_platform")
    op.drop_index(
        "ix_form_intent_type",
        table_name="forms",
        schema="alh_community_platform",
    )
    op.drop_table("forms", schema="alh_community_platform")
    # ### end Alembic commands ###
