[build-system]
requires = ["setuptools>=42", "wheel", "grpcio-tools"]
build-backend = "setuptools.build_meta"

[project]
name = "alumnihub-config-library"
version = "0.1.1"
description = "Config library for AlumniHub community platform"
authors = [
    { name = "Dmitriy Evseev"}
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.12",
    # "License :: OSI Approved :: MIT License", # ToDo: decide on the license
    "Operating System :: OS Independent"
]
dependencies = [
    "pydantic",
    "pydantic_settings"
]
urls = { "Homepage" = "https://github.com/AlumniHubMain/community_platform/" }

[tool.setuptools]
packages = ["alumnihub.community_platform.config_library"]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.package-data]
"alumnihub.community_platform.config_library" = [
    "generated/*_pb2.py",
    "generated/*_pb2.pyi"
]
