[project]
name = "config-library"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "und3v3l0p3d", email = "prohibitme@ya.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.4",
    "pydantic-settings>=2.7.0",
]

[project.scripts]
config-library = "config_library:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
