# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x10matching_service\"\xc5\x01\n\rServiceConfig\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x11\n\tlog_level\x18\x02 \x01(\t\x12\x1b\n\x13google_cloud_bucket\x18\x03 \x01(\t\x12\x17\n\x0fresult_topic_id\x18\x04 \x01(\t\x12\x15\n\rpostgres_host\x18\x05 \x01(\t\x12\x15\n\rpostgres_port\x18\x06 \x01(\x05\x12\x15\n\rpostgres_base\x18\x07 \x01(\t\x12\x12\n\nmodel_path\x18\x08 \x01(\t\"\x97\x01\n\x06\x43onfig\x12,\n\x03\x64\x65v\x18\x01 \x01(\x0b\x32\x1f.matching_service.ServiceConfig\x12-\n\x04prod\x18\x02 \x01(\x0b\x32\x1f.matching_service.ServiceConfig\x12\x30\n\x07staging\x18\x03 \x01(\x0b\x32\x1f.matching_service.ServiceConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVICECONFIG']._serialized_start=35
  _globals['_SERVICECONFIG']._serialized_end=232
  _globals['_CONFIG']._serialized_start=235
  _globals['_CONFIG']._serialized_end=386
# @@protoc_insertion_point(module_scope)
