[project]
name = "event-emitter"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Sergey Sedov", email = "sergey.sedov@gmail.com" },
    { name = "und3v3l0p3d", email = "prohibitme@ya.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "alumni-hub",
    "google-cloud-pubsub>=2.27.1",
    "protobuf>=5.29.2",
    "pydantic>=2.10.4",
]

[project.scripts]
event-emmiter = "event_emmiter:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
alumni-hub = { path = "../alumni_hub" }


[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]

[tool.ruff]
extend = "../../ruff.toml"
