[build-system]
requires = ["setuptools>=42", "wheel", "grpcio-tools"]
build-backend = "setuptools.build_meta"

[project]
name = "alumnihub-event-emitter"
version = "0.1.1"
description = "Notification event emitter for AlumniHub community platform"
authors = [
    { name = "Sergey Sedov", email = "sergey.sedov@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3.12",
    # "License :: OSI Approved :: MIT License", # ToDo: decide on the license
    "Operating System :: OS Independent"
]
dependencies = [
    "google-cloud-pubsub",
    "protobuf",
    "pydantic"
]
urls = { "Homepage" = "https://github.com/AlumniHubMain/community_platform/" }

[tool.setuptools]
packages = ["alumnihub.community_platform.event_emitter"]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.package-data]
"alumnihub.community_platform.event_emitter" = [
    "generated/*_pb2.py",
    "generated/*_pb2.pyi"
]
