[project]
name = "alumni-hub"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "und3v3l0p3d", email = "prohibitme@ya.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "uv-proto-plugin",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
uv-proto-plugin = { path = "../uv_proto_plugin" }

[tool.hatch.build.hooks.protobuf]
dependencies = ["uv-proto-plugin"]
proto_paths = ["proto"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]
